### ISSUE TITLE
Make "Currency Code" field optional

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/microsoft-ads-offline-conversion-tag#5]
Please make the "Currency Code" as an optional field for the "Conversion Data" section:

![Screenshot 2024-07-15 at 15 23 09](https://github.com/user-attachments/assets/d10af3b8-741a-478f-b11f-fd720bd2a987)

Right now this field is required, and it should be optional, as per the documentation:

![Screenshot 2024-07-15 at 15 26 13](https://github.com/user-attachments/assets/8d53296f-a27f-44be-9fc2-ad4c249ede4f)

For example, we work with conversions (Page View & Lead) that do not have any value associated (and therefore any currency associated). For this case scenario, we can't properly configure the tag (omitting the currency code value).

**Comment by alexgarciab** [comment]
@kHorozhanov can you push this quick update to the tag? it should be easy to fix and will help us set up the tag values properly

**Comment by Bukashk0zzz** [comment]
Fixed
